"""cargo del usuario

Revision ID: 63531e6d5a5f
Revises: b37b4fd6e183
Create Date: 2026-09-22 18:38:38.610783

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision: str = '63531e6d5a5f'
down_revision: str | Sequence[str] | None = 'b37b4fd6e183'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cargo', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_column('cargo')

    # ### end Alembic commands ###
