"""Informe: congela las dos corridas y guarda el contenido compuesto.

Tres cambios sobre `informe`:

  id_corrida_agentes   FK nueva. El informe congelaba el ranking y no los
                       insights, asi que podia reconstruir su orden y no su
                       contenido -que es lo que la gerencia lee y califica-.
                       Resuelve A9 sin flag: la corrida canonica de un ciclo es
                       la que referencia su informe publicado.
  contenido            El informe compuesto en JSON. Lo arma M6 desde el
                       almacen; ni una cifra sale del modelo (CA-M6.3).
  uri_html             SE ELIMINA. Con Next.js pintando no hay archivo HTML que
                       referenciar, y una columna muerta con nombre descriptivo
                       es una invitacion a que alguien la rellene.

Mas un indice unico PARCIAL: un solo informe `publicado` por ciclo. Los
archivados no compiten, asi que caben tantas correcciones como hagan falta.

`contenido` entra como NOT NULL sin default: **la tabla esta vacia** en local y
en Neon -M6 no ha publicado nunca- asi que no hay filas que rellenar. Contra una
base con informes habria que darle un default primero.


Revision ID: b37b4fd6e183
Revises: aef93e016610
Create Date: 2026-09-22 07:49:40.917841

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'b37b4fd6e183'
down_revision: str | Sequence[str] | None = 'aef93e016610'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('informe', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_corrida_agentes', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('contenido', sa.JSON(), nullable=False))
        batch_op.create_index(batch_op.f('ix_informe_id_corrida_agentes'), ['id_corrida_agentes'], unique=False)
        batch_op.create_index('uq_informe_publicado_por_ciclo', ['id_ciclo'], unique=True, sqlite_where=sa.text("estado = 'publicado'"), postgresql_where=sa.text("estado = 'publicado'"))
        # Nombrada a proposito: autogenerate la deja en None y en modo batch
        # eso revienta a media migracion. Ver CLAUDE.md 6.1.
        batch_op.create_foreign_key(
            'fk_informe_corrida_agentes', 'corrida_agentes',
            ['id_corrida_agentes'], ['id'],
        )
        batch_op.drop_column('uri_html')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('informe', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uri_html', sa.TEXT(), autoincrement=False, nullable=False))
        batch_op.drop_constraint('fk_informe_corrida_agentes', type_='foreignkey')
        batch_op.drop_index('uq_informe_publicado_por_ciclo', sqlite_where=sa.text("estado = 'publicado'"), postgresql_where=sa.text("estado = 'publicado'"))
        batch_op.drop_index(batch_op.f('ix_informe_id_corrida_agentes'))
        batch_op.drop_column('contenido')
        batch_op.drop_column('id_corrida_agentes')

    # ### end Alembic commands ###
