"""origen del informe: commit e invocacion

Revision ID: d5932c3bdc03
Revises: dd0101cc28ae
Create Date: 2026-09-22 20:34:08.914940

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'd5932c3bdc03'
down_revision: str | Sequence[str] | None = 'dd0101cc28ae'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema.

    En tres pasos y no en uno: la columna es NOT NULL y la tabla **ya tiene
    informes publicados**, así que añadirla directamente falla. Se añade
    anulable, se rellena con `{}` —los informes anteriores a F0.6 no tienen
    origen que declarar, y eso es un hecho, no un hueco— y se cierra.
    """
    with op.batch_alter_table('informe', schema=None) as batch_op:
        batch_op.add_column(sa.Column('origen', sa.JSON(), nullable=True))

    op.execute("UPDATE informe SET origen = '{}' WHERE origen IS NULL")

    with op.batch_alter_table('informe', schema=None) as batch_op:
        batch_op.alter_column('origen', existing_type=sa.JSON(), nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('informe', schema=None) as batch_op:
        batch_op.drop_column('origen')

    # ### end Alembic commands ###
