"""linaje de prompts en insight

`insight.version_prompt` guardaba la etiqueta —"v4"— y nada más. Una etiqueta no
ancla: si alguien edita `clasificador_v4.md` sin renombrarlo, todos los insights
anteriores siguen diciendo v4 y no hay forma de saber que el prompt cambió entre
una pasada y otra. Con dos pasadas del mismo ciclo eso es fatal para A6, porque
la diferencia podría venir del prompt y no del modelo.

`prompt_version` existía desde el esquema inicial y **nadie la escribía**.

Columna nullable: los 45 insights anteriores no registraron su prompt por
contenido y no hay forma honesta de reconstruirlo — el archivo de hoy puede no
ser el que corrió. NULL dice "no se sabe".

Revision ID: a6ac249fcec9
Revises: 1c5b16b87338
Create Date: 2026-09-18 13:53:03.454086

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'a6ac249fcec9'
down_revision: str | Sequence[str] | None = '1c5b16b87338'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('insight', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_prompt', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_insight_id_prompt'), ['id_prompt'], unique=False)
        # Con nombre: autogenerate la deja sin nombrar y en modo batch eso falla.
        batch_op.create_foreign_key(
            'fk_insight_prompt', 'prompt_version', ['id_prompt'], ['id']
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('insight', schema=None) as batch_op:
        batch_op.drop_constraint('fk_insight_prompt', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_insight_id_prompt'))
        batch_op.drop_column('id_prompt')

    # ### end Alembic commands ###
