"""Nomenclator DIVIPOLA: tabla maestra de entidades territoriales.

Crea `entidad_divipola`, que guarda las 1.135 entidades del nomenclator segun
TerriData: 1 nacional, 32 departamentos y 1.102 municipios.

**Sin clave foranea a `municipio`, a proposito.** El MVP procesa 18 municipios
y valida el mecanismo, no la cobertura (PRD 7). Enlazar las dos tablas
sugeriria que el universo se amplio, y no se amplio.

Los codigos siguen la convencion de TerriData —nacional 01001, departamento
dd000, municipio ddmmm— para que un join futuro no tenga que traducir nada.

Revision ID: 14122d0ee975
Revises: bdd6258571ec
Create Date: 2026-09-21 15:02:39.261345

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision: str = '14122d0ee975'
down_revision: str | Sequence[str] | None = 'bdd6258571ec'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entidad_divipola',
    sa.Column('codigo', sa.String(length=5), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('codigo_departamento', sa.String(length=2), nullable=False),
    sa.Column('nombre_departamento', sa.String(length=80), nullable=False),
    sa.Column('tipo', sa.String(length=12), nullable=False),
    sa.CheckConstraint("tipo IN ('nacional', 'departamento', 'municipio')", name='ck_entidad_divipola_tipo'),
    sa.CheckConstraint('length(codigo) = 5', name='ck_entidad_divipola_5_chars'),
    sa.PrimaryKeyConstraint('codigo')
    )
    with op.batch_alter_table('entidad_divipola', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_entidad_divipola_codigo_departamento'), ['codigo_departamento'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entidad_divipola', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_entidad_divipola_codigo_departamento'))

    op.drop_table('entidad_divipola')
    # ### end Alembic commands ###
