"""version de pipeline en corrida de agentes

Revision ID: bdd6258571ec
Revises: 913b0f7b0e12
Create Date: 2026-09-21 10:58:49.376973

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'bdd6258571ec'
down_revision: str | Sequence[str] | None = '913b0f7b0e12'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('corrida_agentes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('version_pipeline', sa.String(length=20), nullable=True))
        batch_op.create_index(
            batch_op.f('ix_corrida_agentes_version_pipeline'), ['version_pipeline'], unique=False
        )

    # Lo que ya corrio fue p1: solo SECOP. Dejarlo en NULL obligaria a
    # deducirlo por la fecha de la corrida.
    op.execute(sa.text("UPDATE corrida_agentes SET version_pipeline = 'p1'"))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('corrida_agentes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_corrida_agentes_version_pipeline'))
        batch_op.drop_column('version_pipeline')

    # ### end Alembic commands ###
