"""identidad: autor de la calificacion y registro de identificaciones

Revision ID: dd0101cc28ae
Revises: 63531e6d5a5f
Create Date: 2026-09-22 18:45:53.910804

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'dd0101cc28ae'
down_revision: str | Sequence[str] | None = '63531e6d5a5f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


FK_AUTOR = "fk_calificacion_id_usuario"


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('identificacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_agent', sa.String(length=300), nullable=True),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('identificacion', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_identificacion_id_usuario'), ['id_usuario'], unique=False)

    with op.batch_alter_table('calificacion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_usuario', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_calificacion_id_usuario'), ['id_usuario'], unique=False)
        # **Con nombre, siempre.** Autogenerate la rinde como `None` y avisa en
        # un UserWarning fácil de pasar por alto; en SQLite, donde todo pasa por
        # modo batch, una foránea sin nombre revienta la migración a medias y el
        # log dice que subió. Ver `CLAUDE.md` §6.1.
        batch_op.create_foreign_key(FK_AUTOR, 'usuario', ['id_usuario'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('calificacion', schema=None) as batch_op:
        batch_op.drop_constraint(FK_AUTOR, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_calificacion_id_usuario'))
        batch_op.drop_column('id_usuario')

    with op.batch_alter_table('identificacion', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_identificacion_id_usuario'))

    op.drop_table('identificacion')
    # ### end Alembic commands ###
