"""esquema inicial del MVP

Línea base de las 12 entidades del PRD §4.2 más el linaje de D7. Hasta aquí el
esquema se venía creando con `Base.metadata.create_all`; esta revisión lo
estampa tal como estaba, así que no cambia nada en una base ya poblada.

Una base de desarrollo anterior a esta migración se pone al día con
`alembic stamp head`, **no** con `alembic upgrade head`: las tablas ya existen y
el upgrade fallaría al intentar crearlas otra vez.

De aquí en adelante rige la regla 2 de D8: ningún cambio de esquema entra por
create_all.

Revision ID: 949a8ff9e15d
Revises:
Create Date: 2026-09-17 13:43:56.744284

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '949a8ff9e15d'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dataset_version',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('uri_blob', sa.Text(), nullable=False),
    sa.Column('hash_sha256', sa.String(length=64), nullable=False),
    sa.Column('n_registros', sa.Integer(), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hash_sha256')
    )
    op.create_table('municipio',
    sa.Column('divipola', sa.String(length=5), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('departamento', sa.String(length=80), nullable=False),
    sa.Column('corredores', sa.JSON(), nullable=False),
    sa.Column('elic', sa.JSON(), nullable=True),
    sa.CheckConstraint('length(divipola) = 5', name='ck_divipola_5_chars'),
    sa.PrimaryKeyConstraint('divipola')
    )
    op.create_table('prompt_version',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agente', sa.String(length=40), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('uri_blob', sa.Text(), nullable=False),
    sa.Column('hash_sha256', sa.String(length=64), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agente', 'version', name='uq_prompt_agente_version')
    )
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_gerencia', sa.String(length=60), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('correo', sa.String(length=160), nullable=False),
    sa.Column('rol', sa.String(length=20), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.CheckConstraint("rol IN ('gerencia', 'administrador')", name='ck_rol'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('correo')
    )
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usuario_id_gerencia'), ['id_gerencia'], unique=False)

    op.create_table('ciclo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha_desde', sa.Date(), nullable=False),
    sa.Column('fecha_hasta', sa.Date(), nullable=False),
    sa.Column('id_dataset', sa.Integer(), nullable=True),
    sa.Column('n_senales', sa.Integer(), nullable=False),
    sa.Column('n_insights', sa.Integer(), nullable=False),
    sa.Column('n_validados', sa.Integer(), nullable=False),
    sa.Column('n_rechazados', sa.Integer(), nullable=False),
    sa.Column('costo_tokens', sa.Float(), nullable=False),
    sa.Column('duracion_seg', sa.Float(), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['id_dataset'], ['dataset_version.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('informe',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_ciclo', sa.Integer(), nullable=False),
    sa.Column('uri_html', sa.Text(), nullable=False),
    sa.Column('infografias', sa.JSON(), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('fecha_publicacion', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['id_ciclo'], ['ciclo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('informe', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_informe_id_ciclo'), ['id_ciclo'], unique=False)

    op.create_table('insight',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_ciclo', sa.Integer(), nullable=False),
    sa.Column('divipola', sa.String(length=5), nullable=False),
    sa.Column('categoria', sa.String(length=60), nullable=False),
    sa.Column('resumen', sa.Text(), nullable=False),
    sa.Column('implicacion_inmobiliaria', sa.Text(), nullable=True),
    sa.Column('evidencia', sa.JSON(), nullable=False),
    sa.Column('ids_senal', sa.JSON(), nullable=False),
    sa.Column('estado_validacion', sa.String(length=20), nullable=False),
    sa.Column('motivo_rechazo', sa.Text(), nullable=True),
    sa.Column('contexto_no_verificado', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("estado_validacion IN ('pendiente', 'validado', 'rechazado')", name='ck_estado_validacion'),
    sa.ForeignKeyConstraint(['divipola'], ['municipio.divipola'], ),
    sa.ForeignKeyConstraint(['id_ciclo'], ['ciclo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('insight', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_insight_divipola'), ['divipola'], unique=False)
        batch_op.create_index(batch_op.f('ix_insight_id_ciclo'), ['id_ciclo'], unique=False)

    op.create_table('score_municipio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_ciclo', sa.Integer(), nullable=False),
    sa.Column('divipola', sa.String(length=5), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('ranking', sa.Integer(), nullable=True),
    sa.Column('factores', sa.JSON(), nullable=False),
    sa.Column('dias_cubiertos', sa.Integer(), nullable=True),
    sa.Column('dias_ventana', sa.Integer(), nullable=True),
    sa.Column('sin_cobertura', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['divipola'], ['municipio.divipola'], ),
    sa.ForeignKeyConstraint(['id_ciclo'], ['ciclo.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_ciclo', 'divipola', name='uq_score_ciclo_municipio')
    )
    with op.batch_alter_table('score_municipio', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_score_municipio_divipola'), ['divipola'], unique=False)
        batch_op.create_index(batch_op.f('ix_score_municipio_id_ciclo'), ['id_ciclo'], unique=False)

    op.create_table('seguimiento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('divipola', sa.String(length=5), nullable=False),
    sa.Column('id_ciclo_origen', sa.Integer(), nullable=False),
    sa.Column('estado', sa.String(length=30), nullable=False),
    sa.Column('nota', sa.Text(), nullable=True),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.Column('fecha_cambio', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("estado IN ('priorizado', 'en_revision', 'en_estructuracion', 'descartado')", name='ck_estado_seguimiento'),
    sa.ForeignKeyConstraint(['divipola'], ['municipio.divipola'], ),
    sa.ForeignKeyConstraint(['id_ciclo_origen'], ['ciclo.id'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('seguimiento', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_seguimiento_divipola'), ['divipola'], unique=False)

    op.create_table('senal_cruda',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_ciclo', sa.Integer(), nullable=False),
    sa.Column('divipola', sa.String(length=5), nullable=False),
    sa.Column('fuente', sa.String(length=20), nullable=False),
    sa.Column('id_externo', sa.String(length=120), nullable=True),
    sa.Column('fecha_publicacion', sa.Date(), nullable=True),
    sa.Column('contenido', sa.Text(), nullable=False),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('hash_dedup', sa.String(length=64), nullable=False),
    sa.Column('uri_blob', sa.Text(), nullable=True),
    sa.Column('datos', sa.JSON(), nullable=True),
    sa.Column('capturado_en', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['divipola'], ['municipio.divipola'], ),
    sa.ForeignKeyConstraint(['id_ciclo'], ['ciclo.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_ciclo', 'hash_dedup', name='uq_senal_ciclo_hash')
    )
    with op.batch_alter_table('senal_cruda', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_senal_cruda_divipola'), ['divipola'], unique=False)
        batch_op.create_index(batch_op.f('ix_senal_cruda_fecha_publicacion'), ['fecha_publicacion'], unique=False)
        batch_op.create_index(batch_op.f('ix_senal_cruda_fuente'), ['fuente'], unique=False)
        batch_op.create_index(batch_op.f('ix_senal_cruda_hash_dedup'), ['hash_dedup'], unique=False)
        batch_op.create_index(batch_op.f('ix_senal_cruda_id_ciclo'), ['id_ciclo'], unique=False)

    op.create_table('traza_agente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_ciclo', sa.Integer(), nullable=False),
    sa.Column('agente', sa.String(length=40), nullable=False),
    sa.Column('modelo', sa.String(length=80), nullable=True),
    sa.Column('id_prompt', sa.Integer(), nullable=True),
    sa.Column('id_dataset', sa.Integer(), nullable=True),
    sa.Column('hash_input', sa.String(length=64), nullable=True),
    sa.Column('hash_output', sa.String(length=64), nullable=True),
    sa.Column('tokens_entrada', sa.Integer(), nullable=True),
    sa.Column('tokens_salida', sa.Integer(), nullable=True),
    sa.Column('tokens_cache_lectura', sa.Integer(), nullable=True),
    sa.Column('duracion_ms', sa.Integer(), nullable=True),
    sa.Column('id_traza_langfuse', sa.String(length=80), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['id_ciclo'], ['ciclo.id'], ),
    sa.ForeignKeyConstraint(['id_dataset'], ['dataset_version.id'], ),
    sa.ForeignKeyConstraint(['id_prompt'], ['prompt_version.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('traza_agente', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_traza_agente_agente'), ['agente'], unique=False)
        batch_op.create_index(batch_op.f('ix_traza_agente_id_ciclo'), ['id_ciclo'], unique=False)

    op.create_table('calificacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_insight', sa.Integer(), nullable=False),
    sa.Column('id_gerencia', sa.String(length=60), nullable=False),
    sa.Column('valor', sa.Integer(), nullable=False),
    sa.Column('comentario', sa.Text(), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('valor BETWEEN 1 AND 5', name='ck_valor_1_5'),
    sa.ForeignKeyConstraint(['id_insight'], ['insight.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_insight', 'id_gerencia', name='uq_calificacion_insight_gerencia')
    )
    with op.batch_alter_table('calificacion', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_calificacion_id_gerencia'), ['id_gerencia'], unique=False)
        batch_op.create_index(batch_op.f('ix_calificacion_id_insight'), ['id_insight'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('calificacion', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_calificacion_id_insight'))
        batch_op.drop_index(batch_op.f('ix_calificacion_id_gerencia'))

    op.drop_table('calificacion')
    with op.batch_alter_table('traza_agente', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_traza_agente_id_ciclo'))
        batch_op.drop_index(batch_op.f('ix_traza_agente_agente'))

    op.drop_table('traza_agente')
    with op.batch_alter_table('senal_cruda', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_senal_cruda_id_ciclo'))
        batch_op.drop_index(batch_op.f('ix_senal_cruda_hash_dedup'))
        batch_op.drop_index(batch_op.f('ix_senal_cruda_fuente'))
        batch_op.drop_index(batch_op.f('ix_senal_cruda_fecha_publicacion'))
        batch_op.drop_index(batch_op.f('ix_senal_cruda_divipola'))

    op.drop_table('senal_cruda')
    with op.batch_alter_table('seguimiento', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_seguimiento_divipola'))

    op.drop_table('seguimiento')
    with op.batch_alter_table('score_municipio', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_score_municipio_id_ciclo'))
        batch_op.drop_index(batch_op.f('ix_score_municipio_divipola'))

    op.drop_table('score_municipio')
    with op.batch_alter_table('insight', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_insight_id_ciclo'))
        batch_op.drop_index(batch_op.f('ix_insight_divipola'))

    op.drop_table('insight')
    with op.batch_alter_table('informe', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_informe_id_ciclo'))

    op.drop_table('informe')
    op.drop_table('ciclo')
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usuario_id_gerencia'))

    op.drop_table('usuario')
    op.drop_table('prompt_version')
    op.drop_table('municipio')
    op.drop_table('dataset_version')
    # ### end Alembic commands ###
