"""valores crudos de los factores en plano

Decision de Analitica (pendiente A5): **no se ancla hoy una escala absoluta**,
porque habria que inventar los topes sin datos. Se guardan los valores sin
normalizar para poder construirla en la semana 8 con 3 ciclos de evidencia, y
mientras tanto el score min-max sigue mandando el ranking.

Es el **mismo dato** que `factores["aportes"][i]["crudo"]`, en plano. Se duplica
a proposito: construir una escala absoluta desde un array anidado obliga a un
script, y desde una columna plana es un SELECT. La comparacion entre corridas
—que es el punto entero de guardarlos— pasa de programa a consulta.

Nullable con default vacio: las corridas anteriores lo tendran en {}. Sus
valores crudos siguen estando dentro de `factores`, asi que nada se pierde; lo
que falta es la comodidad de consulta, y rellenarlas exigiria releer el JSON de
cada fila para escribirlo dos veces.

Revision ID: 913b0f7b0e12
Revises: a6ac249fcec9
Create Date: 2026-09-18 14:13:48.715141

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '913b0f7b0e12'
down_revision: str | Sequence[str] | None = 'a6ac249fcec9'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('score_municipio', schema=None) as batch_op:
        batch_op.add_column(sa.Column('valores_crudos', sa.JSON(), nullable=False, server_default='{}'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('score_municipio', schema=None) as batch_op:
        batch_op.drop_column('valores_crudos')

    # ### end Alembic commands ###
