"""Contexto municipal estructural desde TerriData.

Crea `contexto_municipal`: una fila por municipio con poblacion, valor
agregado, deficit habitacional y catastro urbano, cada uno con su anio.

**Sin clave foranea a `municipio` ni a `entidad_divipola`, a proposito.** Se
cargan los 1.102 municipios porque hacen falta para calcular los cuartiles
nacionales de las bandas, pero el MVP sigue procesando 18. Enlazar sugeriria
que la cobertura crecio.

**Esta tabla NO alimenta el scoring.** Todos sus indicadores son anuales y
serian identicos en los tres ciclos del MVP, que es el defecto de F4 que acaba
de corregirse. Alimenta al Correlacionador, y bandeada.


Revision ID: aef93e016610
Revises: 14122d0ee975
Create Date: 2026-09-21 15:19:50.852022

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'aef93e016610'
down_revision: str | Sequence[str] | None = '14122d0ee975'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contexto_municipal',
    sa.Column('codigo_divipola', sa.String(length=5), nullable=False),
    sa.Column('poblacion_total', sa.Integer(), nullable=True),
    sa.Column('anio_poblacion', sa.Integer(), nullable=True),
    sa.Column('valor_agregado', sa.Float(), nullable=True),
    sa.Column('anio_valor_agregado', sa.Integer(), nullable=True),
    sa.Column('deficit_cuantitativo', sa.Float(), nullable=True),
    sa.Column('deficit_cualitativo', sa.Float(), nullable=True),
    sa.Column('anio_deficit', sa.Integer(), nullable=True),
    sa.Column('avaluo_catastral_urbano', sa.Float(), nullable=True),
    sa.Column('predios_urbanos', sa.Integer(), nullable=True),
    sa.Column('anio_catastro', sa.Integer(), nullable=True),
    sa.CheckConstraint('length(codigo_divipola) = 5', name='ck_contexto_municipal_5_chars'),
    sa.PrimaryKeyConstraint('codigo_divipola')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contexto_municipal')
    # ### end Alembic commands ###
