"""registro de descartes del clasificador

CA-M2.5 exige registrar en la traza **qué se descartó y por qué**. El agente ya
producía los descartes con su motivo y `ciclo.py` los tiraba, así que la tasa de
reducción de CA-M2.1 no era auditable: quedaba el numerador —los insights— y el
denominador se perdía con el proceso.

Tabla nueva, nada que migrar: los descartes de las pasadas anteriores no se
registraron y no hay forma honesta de reconstruirlos.

Cuelga de la corrida, no del par (ciclo, municipio): dos pasadas descartan cosas
distintas, y comparar qué descartó cada una es parte de medir A6.

Revision ID: 1c5b16b87338
Revises: cb034d1c967b
Create Date: 2026-09-18 13:26:23.533935

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision: str = '1c5b16b87338'
down_revision: str | Sequence[str] | None = 'cb034d1c967b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('descarte',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_corrida', sa.Integer(), nullable=False),
    sa.Column('id_senal', sa.Integer(), nullable=False),
    sa.Column('motivo', sa.Text(), nullable=False),
    sa.Column('declarado', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['id_corrida'], ['corrida_agentes.id'], ),
    sa.ForeignKeyConstraint(['id_senal'], ['senal_cruda.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_corrida', 'id_senal', name='uq_descarte_corrida_senal')
    )
    with op.batch_alter_table('descarte', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_descarte_declarado'), ['declarado'], unique=False)
        batch_op.create_index(batch_op.f('ix_descarte_id_corrida'), ['id_corrida'], unique=False)
        batch_op.create_index(batch_op.f('ix_descarte_id_senal'), ['id_senal'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('descarte', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_descarte_id_senal'))
        batch_op.drop_index(batch_op.f('ix_descarte_id_corrida'))
        batch_op.drop_index(batch_op.f('ix_descarte_declarado'))

    op.drop_table('descarte')
    # ### end Alembic commands ###
